### ISSUE TITLE
[1.15.2] Feature Request - More Config Options

### ISSUE THREAD

**Issue by curlywaffles** [MC-U-Team/Useful-Ores#6]
Not a bug, more of a feature request.

Would it be possible for you to include a config to enable/disable certain elements? Maybe by metal type? One for each type. It would also disable it generating in the world.

bronze=true
etc etc.

**Comment by HyCraftHD** [comment]
Hm would be a consideration but I'm don't really like the idea to remove or add registry types with a config (Thats also not possible since 1.13).
The generation can be disabled with a datapack (the wiki for that will be up soon).
Currently this mod has not really any use, its just for some other tech mod projects i'm working on to generalize resources.

**Comment by curlywaffles** [comment]
Ok cool will wait for the wiki. I was going to use it for a pack I'm working on using Crafttweaker. I can disable them with that a config just would have been easier :). Thanks for the reply.
